In [16]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import warnings 
warnings.filterwarnings("ignore")

In [2]:
test=pd.read_csv(r"/Users/vivekrajashekaran/Downloads/digit-recognizer/test.csv")
train=pd.read_csv(r"/Users/vivekrajashekaran/Downloads/digit-recognizer/train.csv")

In [3]:
train.shape,test.shape

((42000, 785), (28000, 784))

In [4]:
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

Logistic Regression

*logistic regression can handle multi class problem

In [4]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()

##splitting into x and y

x=train.drop("label",axis=1)
y=train.label

## building the model

pred=lg.fit(x,y).predict(test)
pred

array([2, 0, 9, ..., 3, 9, 2])

In [17]:
submission=pd.read_csv(r"/Users/vivekrajashekaran/Downloads/digit-recognizer/sample_submission.csv")
submission

ImageId  Label
0            1      0
1            2      0
2            3      0
3            4      0
4            5      0
...        ...    ...
27995    27996      0
27996    27997      0
27997    27998      0
27998    27999      0
27999    28000      0

[28000 rows x 2 columns]

In [7]:
submission["Label"]=pred

In [8]:
submission.to_csv(r"/Users/vivekrajashekaran/Downloads/digit-recognizer/logistics.csv",index=False)

Decision Tree Classifier

In [9]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()

#building the model
pred_tree=dtree.fit(x,y).predict(test)

pred_tree

array([2, 2, 9, ..., 3, 4, 2])

In [10]:
submission["Label"]=pred_tree
submission.to_csv(r"/Users/vivekrajashekaran/Downloads/digit-recognizer/Decision_tree.csv",index=False) #0.8590

Random forest classifier

In [11]:
from sklearn.ensemble  import RandomForestClassifier
rf=RandomForestClassifier()

## building the model
pred_rf=rf.fit(x,y).predict(test)

pred_rf



array([2, 0, 9, ..., 3, 9, 2])

In [12]:
## submission
submission["Label"]=pred_rf
submission.to_csv(r"/Users/vivekrajashekaran/Downloads/digit-recognizer/Random_forest.csv",index=False)

ADA Boost

In [13]:
from sklearn.ensemble import AdaBoostClassifier
adb=AdaBoostClassifier(learning_rate=0.1,n_estimators=100)

#building the model
pred_adb=adb.fit(x,y).predict(test)

In [14]:
submission["Label"]=pred_adb
submission.to_csv(r"/Users/vivekrajashekaran/Documents/projects/ML_models/Digit_Recogoniser/adb.csv",index=False)

Gradient Boosting classifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gbm=GradientBoostingClassifier()

#model building
pred_gbm=gbm.fit(x,y).predict(test)

#submission
submission["Label"]=pred_gbm
submission.to_csv(r"/Users/vivekrajashekaran/Documents/projects/ML_models/Digit_Recogoniser/gradient_boosting.csv",index=False)


Light gradient Boosting

In [18]:
from lightgbm import LGBMClassifier
lgbm = LGBMClassifier()
pred_lgbm = lgbm.fit(x, y).predict(test)

submission['Label'] = pred_lgbm
submission.to_csv('submission_lgbm.csv', index = False)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.043368 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 105387
[LightGBM] [Info] Number of data points in the train set: 42000, number of used features: 620
[LightGBM] [Info] Start training from score -2.318908
[LightGBM] [Info] Start training from score -2.193517
[LightGBM] [Info] Start training from score -2.308076
[LightGBM] [Info] Start training from score -2.267264
[LightGBM] [Info] Start training from score -2.333535
[LightGBM] [Info] Start training from score -2.403985
[LightGBM] [Info] Start training from score -2.317699
[LightGBM] [Info] Start training from score -2.255838
[LightGBM] [Info] Start training from score -2.335748
[LightGBM] [Info] Start training from score -2.305446
